name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
          secrets:
            MARKETSTACK_API_TOKEN
            MORALIS_APPID
            MORALIS_SERVERURL
            MORALIS_APPKEY
        env: 
          MARKETSTACK_API_TOKEN: ${{ secrets.MARKETSTACK_API_TOKEN }}
          MORALIS_APPID: ${{ secrets.MORALIS_APPID }}
          MORALIS_SERVERURL: ${{ secrets.MORALIS_SERVERURL }}
          MORALIS_APPKEY: ${{ secrets.MORALIS_APPKEY }}
